# This is an autogenerated template from the python library: cluster
# Please set the below flags if they have not been filled in
#$ -l tmem=3G
#$ -l h_vmem=3G
#$ -l h_rt=14400
#$ -j y
#$ -l gpu=false
#$ -S /bin/bash
#$ -N mmd_learning_curves_over_tasks_hypercube_with_k_vertex_gaussians
#$ -t 1-24

SGE_TASK_ID=4
CURRENT_JOB_OUTPUT_DIR=/home/isak/life/references/projects/phd/active_meta_learning/src/active_meta_learning_py/active_meta_learning/data/job_output/mmd_learning_curves_over_tasks_hypercube_with_k_vertex_gaussians
mkdir -p ${CURRENT_JOB_OUTPUT_DIR}
RUN_OUTPUT_DIR=${CURRENT_JOB_OUTPUT_DIR}/n${SGE_TASK_ID}

hostname
date
python3 /home/isak/life/references/projects/phd/active_meta_learning/src/active_meta_learning_py/active_meta_learning/scripts/mmd_learning_curves_over_tasks_hypercube_with_k_vertex_gaussians.py --csv_path /home/isak/life/references/projects/phd/active_meta_learning/src/active_meta_learning_py/active_meta_learning/data/interim/mmd_learning_curves_over_tasks_hypercube_with_k_vertex_gaussians.csv --extract_line ${SGE_TASK_ID} --output_dir ${CURRENT_JOB_OUTPUT_DIR}
date
